# Generated by Django 5.0.3 on 2024-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_aktif_blog_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
