# Generated by Django 5.0.3 on 2024-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_title_category_name_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs', verbose_name='Resim'),
        ),
    ]
