# Generated by Django 5.0.3 on 2024-03-28 14:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blog_is_home_alter_blog_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makinelerimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Makine adı')),
                ('image', models.ImageField(upload_to='blogs', verbose_name='Resim')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('is_active', models.BooleanField(verbose_name='Yayında mı?')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
