# Generated by Django 5.0.3 on 2024-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_hakkimizda'),
    ]

    operations = [
        migrations.CreateModel(
            name='İletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_1', models.CharField(max_length=200, verbose_name='1.Kişi Adın')),
                ('tel_1', models.CharField(max_length=200, verbose_name='1.Kişi Telefon')),
                ('Ad_2', models.CharField(max_length=200, verbose_name='2.Kişi Adın')),
                ('tel_2', models.CharField(max_length=200, verbose_name='2.Kişi Telefon')),
                ('adres', models.CharField(max_length=200, verbose_name='Açık adres')),
                ('mail', models.CharField(blank=True, max_length=200, verbose_name='mail')),
            ],
        ),
    ]
